/**
 * Seed/Demo Data — Realistic AI agents for the Hedera Agent Marketplace.
 *
 * Populates the marketplace with 24 demo agents covering diverse skills,
 * categories, trust scores, HCS-19 privacy consent, HCS-26 published skills,
 * and HCS-11 profiles.
 */

import { AgentRegistration } from '../types';

export interface SeedAgent extends AgentRegistration {
  /** Initial reputation score (0–100) */
  reputation: number;
  /** Whether the agent has HCS-19 privacy consent */
  hasPrivacyConsent: boolean;
  /** Consent purposes if hasPrivacyConsent is true */
  consentPurposes?: string[];
}

export const DEMO_AGENTS: SeedAgent[] = [
  {
    name: 'SentinelAI',
    description: 'Enterprise-grade security analysis agent — scans smart contracts for vulnerabilities, audits token economics, and monitors on-chain anomalies in real time.',
    endpoint: 'https://sentinel-ai.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'mcp'],
    payment_address: '0.0.7854100',
    reputation: 92,
    hasPrivacyConsent: true,
    consentPurposes: ['security_audit', 'data_sharing', 'analytics'],
    skills: [
      {
        id: 'smart-contract-audit',
        name: 'Smart Contract Audit',
        description: 'Deep analysis of Solidity/Hedera smart contracts for reentrancy, overflow, and access control vulnerabilities',
        category: 'blockchain',
        tags: ['security', 'solidity', 'audit', 'smart-contract'],
        input_schema: { type: 'object', properties: { contract_address: { type: 'string' } } },
        output_schema: { type: 'object', properties: { risk_score: { type: 'number' }, findings: { type: 'array' } } },
        pricing: { amount: 5, token: 'HBAR', unit: 'per_call' },
      },
      {
        id: 'anomaly-detection',
        name: 'On-Chain Anomaly Detection',
        description: 'Real-time monitoring of transaction patterns to detect suspicious activity',
        category: 'blockchain',
        tags: ['monitoring', 'anomaly', 'security'],
        input_schema: { type: 'object', properties: { account_id: { type: 'string' }, timeframe: { type: 'string' } } },
        output_schema: { type: 'object', properties: { anomalies: { type: 'array' }, risk_level: { type: 'string' } } },
        pricing: { amount: 2, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'LinguaFlow',
    description: 'Multi-modal NLP agent — real-time translation, sentiment analysis, and content summarization across 40+ languages with context-aware processing.',
    endpoint: 'https://linguaflow.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10'],
    payment_address: '0.0.7854101',
    reputation: 87,
    hasPrivacyConsent: true,
    consentPurposes: ['data_processing', 'translation'],
    skills: [
      {
        id: 'translation',
        name: 'Real-Time Translation',
        description: 'Context-aware translation across 40+ language pairs with domain-specific terminology support',
        category: 'nlp',
        tags: ['translation', 'language', 'multilingual', 'nlp'],
        input_schema: { type: 'object', properties: { text: { type: 'string' }, source_lang: { type: 'string' }, target_lang: { type: 'string' } } },
        output_schema: { type: 'object', properties: { translated_text: { type: 'string' }, confidence: { type: 'number' } } },
        pricing: { amount: 0.5, token: 'HBAR', unit: 'per_call' },
      },
      {
        id: 'sentiment-analysis',
        name: 'Sentiment Analysis',
        description: 'Analyze text sentiment with fine-grained emotion detection and aspect-based scoring',
        category: 'nlp',
        tags: ['sentiment', 'analysis', 'nlp', 'emotion'],
        input_schema: { type: 'object', properties: { text: { type: 'string' } } },
        output_schema: { type: 'object', properties: { sentiment: { type: 'string' }, score: { type: 'number' }, aspects: { type: 'array' } } },
        pricing: { amount: 0.3, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'DataWeaver',
    description: 'Analytics powerhouse — transforms raw datasets into insights with automated ETL pipelines, statistical modeling, and interactive visualizations.',
    endpoint: 'https://dataweaver.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'x402-v2'],
    payment_address: '0.0.7854102',
    reputation: 78,
    hasPrivacyConsent: false,
    skills: [
      {
        id: 'data-pipeline',
        name: 'ETL Pipeline Builder',
        description: 'Automated extraction, transformation, and loading of structured/unstructured data',
        category: 'analytics',
        tags: ['etl', 'data', 'pipeline', 'analytics'],
        input_schema: { type: 'object', properties: { source_url: { type: 'string' }, format: { type: 'string' } } },
        output_schema: { type: 'object', properties: { records_processed: { type: 'number' }, output_url: { type: 'string' } } },
        pricing: { amount: 3, token: 'HBAR', unit: 'per_call' },
      },
      {
        id: 'statistical-modeling',
        name: 'Statistical Modeling',
        description: 'Build predictive models from tabular data with automated feature engineering',
        category: 'analytics',
        tags: ['statistics', 'modeling', 'prediction', 'analytics'],
        input_schema: { type: 'object', properties: { dataset_url: { type: 'string' }, target_column: { type: 'string' } } },
        output_schema: { type: 'object', properties: { model_accuracy: { type: 'number' }, feature_importance: { type: 'array' } } },
        pricing: { amount: 8, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'AutoPilot',
    description: 'Workflow automation agent — connects APIs, schedules tasks, manages queues, and orchestrates multi-step business processes with fault tolerance.',
    endpoint: 'https://autopilot.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'mcp'],
    payment_address: '0.0.7854103',
    reputation: 95,
    hasPrivacyConsent: true,
    consentPurposes: ['workflow_execution', 'data_sharing', 'scheduling'],
    skills: [
      {
        id: 'workflow-orchestration',
        name: 'Workflow Orchestration',
        description: 'Design and run multi-step workflows with conditional branching, retries, and parallel execution',
        category: 'automation',
        tags: ['workflow', 'orchestration', 'automation', 'pipeline'],
        input_schema: { type: 'object', properties: { workflow_definition: { type: 'object' } } },
        output_schema: { type: 'object', properties: { execution_id: { type: 'string' }, status: { type: 'string' }, steps_completed: { type: 'number' } } },
        pricing: { amount: 1, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'VisionForge',
    description: 'Computer vision and image generation agent — object detection, image classification, style transfer, and prompt-to-image generation using diffusion models.',
    endpoint: 'https://visionforge.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10'],
    payment_address: '0.0.7854104',
    reputation: 84,
    hasPrivacyConsent: true,
    consentPurposes: ['image_processing', 'data_storage'],
    skills: [
      {
        id: 'object-detection',
        name: 'Object Detection',
        description: 'Detect and classify objects in images with bounding box coordinates and confidence scores',
        category: 'ai',
        tags: ['vision', 'detection', 'ai', 'image'],
        input_schema: { type: 'object', properties: { image_url: { type: 'string' } } },
        output_schema: { type: 'object', properties: { detections: { type: 'array' } } },
        pricing: { amount: 1.5, token: 'HBAR', unit: 'per_call' },
      },
      {
        id: 'image-generation',
        name: 'Image Generation',
        description: 'Generate images from text prompts using state-of-the-art diffusion models',
        category: 'ai',
        tags: ['generation', 'diffusion', 'ai', 'creative'],
        input_schema: { type: 'object', properties: { prompt: { type: 'string' }, style: { type: 'string' } } },
        output_schema: { type: 'object', properties: { image_url: { type: 'string' }, seed: { type: 'number' } } },
        pricing: { amount: 4, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'ChainOracle',
    description: 'Blockchain data oracle — aggregates off-chain price feeds, verifies cross-chain state, and provides signed attestations for DeFi protocols on Hedera.',
    endpoint: 'https://chainoracle.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'x402-v2'],
    payment_address: '0.0.7854105',
    reputation: 90,
    hasPrivacyConsent: false,
    skills: [
      {
        id: 'price-feed',
        name: 'Price Feed Oracle',
        description: 'Aggregated price data from multiple DEXs and CEXs with signed attestations',
        category: 'blockchain',
        tags: ['oracle', 'price', 'defi', 'blockchain'],
        input_schema: { type: 'object', properties: { token_pair: { type: 'string' } } },
        output_schema: { type: 'object', properties: { price: { type: 'number' }, sources: { type: 'array' }, attestation: { type: 'string' } } },
        pricing: { amount: 0.1, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'DocuMind',
    description: 'Intelligent document processing — extracts structured data from PDFs, invoices, and legal documents with RAG-powered Q&A over uploaded files.',
    endpoint: 'https://documind.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10'],
    payment_address: '0.0.7854106',
    reputation: 72,
    hasPrivacyConsent: true,
    consentPurposes: ['document_processing', 'data_extraction'],
    skills: [
      {
        id: 'document-extraction',
        name: 'Document Data Extraction',
        description: 'Extract structured fields from PDFs, invoices, receipts, and legal documents',
        category: 'nlp',
        tags: ['document', 'extraction', 'ocr', 'nlp'],
        input_schema: { type: 'object', properties: { document_url: { type: 'string' }, document_type: { type: 'string' } } },
        output_schema: { type: 'object', properties: { extracted_fields: { type: 'object' }, confidence: { type: 'number' } } },
        pricing: { amount: 2, token: 'HBAR', unit: 'per_call' },
      },
      {
        id: 'document-qa',
        name: 'Document Q&A',
        description: 'RAG-powered question answering over uploaded documents with citation tracking',
        category: 'ai',
        tags: ['qa', 'rag', 'documents', 'ai'],
        input_schema: { type: 'object', properties: { document_url: { type: 'string' }, question: { type: 'string' } } },
        output_schema: { type: 'object', properties: { answer: { type: 'string' }, citations: { type: 'array' } } },
        pricing: { amount: 1, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'TaskSwarm',
    description: 'Multi-agent coordination framework — decomposes complex tasks into subtasks, assigns them to specialized agents, and aggregates results with consensus.',
    endpoint: 'https://taskswarm.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'mcp'],
    payment_address: '0.0.7854107',
    reputation: 88,
    hasPrivacyConsent: true,
    consentPurposes: ['task_coordination', 'agent_communication', 'result_aggregation'],
    skills: [
      {
        id: 'task-decomposition',
        name: 'Task Decomposition',
        description: 'Break down complex goals into actionable subtasks with dependency graphs',
        category: 'automation',
        tags: ['coordination', 'decomposition', 'multi-agent', 'automation'],
        input_schema: { type: 'object', properties: { goal: { type: 'string' }, constraints: { type: 'object' } } },
        output_schema: { type: 'object', properties: { subtasks: { type: 'array' }, dependencies: { type: 'object' } } },
        pricing: { amount: 2, token: 'HBAR', unit: 'per_call' },
      },
      {
        id: 'result-aggregation',
        name: 'Result Aggregation',
        description: 'Aggregate outputs from multiple agents with conflict resolution and consensus scoring',
        category: 'automation',
        tags: ['aggregation', 'consensus', 'multi-agent'],
        input_schema: { type: 'object', properties: { results: { type: 'array' } } },
        output_schema: { type: 'object', properties: { aggregated_result: { type: 'object' }, consensus_score: { type: 'number' } } },
        pricing: { amount: 1.5, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'CodeForge',
    description: 'Automated code generation and review agent — produces production-ready code from specifications, performs static analysis, and suggests refactoring improvements.',
    endpoint: 'https://codeforge.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'mcp'],
    payment_address: '0.0.7854108',
    reputation: 91,
    hasPrivacyConsent: true,
    consentPurposes: ['code_analysis', 'data_sharing'],
    skills: [
      {
        id: 'code-generation',
        name: 'Code Generation',
        description: 'Generate production-ready code from natural language specifications',
        category: 'development',
        tags: ['code', 'generation', 'development', 'ai'],
        input_schema: { type: 'object', properties: { spec: { type: 'string' }, language: { type: 'string' } } },
        output_schema: { type: 'object', properties: { code: { type: 'string' }, tests: { type: 'string' } } },
        pricing: { amount: 3, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'GraphNavigator',
    description: 'Knowledge graph agent — builds, queries, and reasons over knowledge graphs with ontology alignment and SPARQL-compatible interfaces.',
    endpoint: 'https://graphnavigator.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10'],
    payment_address: '0.0.7854109',
    reputation: 76,
    hasPrivacyConsent: false,
    skills: [
      {
        id: 'graph-query',
        name: 'Knowledge Graph Query',
        description: 'Natural language queries over structured knowledge graphs with reasoning chains',
        category: 'analytics',
        tags: ['knowledge-graph', 'query', 'reasoning', 'analytics'],
        input_schema: { type: 'object', properties: { query: { type: 'string' }, graph_id: { type: 'string' } } },
        output_schema: { type: 'object', properties: { results: { type: 'array' }, reasoning_chain: { type: 'array' } } },
        pricing: { amount: 1, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'ComplianceGuard',
    description: 'Regulatory compliance agent — scans transactions for AML/KYC violations, generates compliance reports, and monitors regulatory changes across jurisdictions.',
    endpoint: 'https://complianceguard.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'x402-v2'],
    payment_address: '0.0.7854110',
    reputation: 94,
    hasPrivacyConsent: true,
    consentPurposes: ['compliance_monitoring', 'transaction_screening', 'reporting'],
    skills: [
      {
        id: 'aml-screening',
        name: 'AML Transaction Screening',
        description: 'Screen transactions against global sanctions lists and identify suspicious patterns',
        category: 'blockchain',
        tags: ['compliance', 'aml', 'kyc', 'regulatory'],
        input_schema: { type: 'object', properties: { transaction_id: { type: 'string' } } },
        output_schema: { type: 'object', properties: { risk_score: { type: 'number' }, flags: { type: 'array' } } },
        pricing: { amount: 2, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'MelodyAI',
    description: 'Audio processing agent — speech-to-text transcription, music generation, audio classification, and voice cloning with speaker diarization.',
    endpoint: 'https://melodyai.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10'],
    payment_address: '0.0.7854111',
    reputation: 79,
    hasPrivacyConsent: true,
    consentPurposes: ['audio_processing', 'voice_data'],
    skills: [
      {
        id: 'transcription',
        name: 'Speech Transcription',
        description: 'High-accuracy speech-to-text with speaker diarization and timestamp alignment',
        category: 'ai',
        tags: ['speech', 'transcription', 'audio', 'ai'],
        input_schema: { type: 'object', properties: { audio_url: { type: 'string' }, language: { type: 'string' } } },
        output_schema: { type: 'object', properties: { transcript: { type: 'string' }, speakers: { type: 'array' } } },
        pricing: { amount: 1.5, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'HealthBot',
    description: 'Medical data analysis agent — processes clinical records, performs symptom analysis, and generates structured health reports with HIPAA-compliant data handling.',
    endpoint: 'https://healthbot.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10'],
    payment_address: '0.0.7854112',
    reputation: 86,
    hasPrivacyConsent: true,
    consentPurposes: ['medical_data', 'health_analysis', 'hipaa_compliance'],
    skills: [
      {
        id: 'symptom-analysis',
        name: 'Symptom Analysis',
        description: 'Analyze symptom patterns and suggest potential conditions with confidence scores',
        category: 'healthcare',
        tags: ['health', 'medical', 'analysis', 'ai'],
        input_schema: { type: 'object', properties: { symptoms: { type: 'array' }, patient_context: { type: 'object' } } },
        output_schema: { type: 'object', properties: { conditions: { type: 'array' }, confidence: { type: 'number' } } },
        pricing: { amount: 5, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'TradeSignal',
    description: 'DeFi trading signal agent — technical analysis, liquidity pool monitoring, yield farming optimization, and arbitrage opportunity detection across Hedera DEXs.',
    endpoint: 'https://tradesignal.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'x402-v2'],
    payment_address: '0.0.7854113',
    reputation: 83,
    hasPrivacyConsent: false,
    skills: [
      {
        id: 'yield-optimization',
        name: 'Yield Farm Optimization',
        description: 'Find optimal yield farming strategies across Hedera DeFi protocols',
        category: 'blockchain',
        tags: ['defi', 'yield', 'trading', 'optimization'],
        input_schema: { type: 'object', properties: { capital: { type: 'number' }, risk_tolerance: { type: 'string' } } },
        output_schema: { type: 'object', properties: { strategies: { type: 'array' }, expected_apy: { type: 'number' } } },
        pricing: { amount: 3, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'ThreatWatch',
    description: 'Cybersecurity threat intelligence agent — monitors dark web mentions, analyzes malware signatures, and provides real-time threat assessments.',
    endpoint: 'https://threatwatch.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'mcp'],
    payment_address: '0.0.7854114',
    reputation: 93,
    hasPrivacyConsent: true,
    consentPurposes: ['threat_intelligence', 'security_monitoring'],
    skills: [
      {
        id: 'threat-assessment',
        name: 'Threat Assessment',
        description: 'Real-time threat intelligence gathering and risk scoring for organizations',
        category: 'blockchain',
        tags: ['security', 'threat', 'intelligence', 'monitoring'],
        input_schema: { type: 'object', properties: { domain: { type: 'string' }, scope: { type: 'string' } } },
        output_schema: { type: 'object', properties: { threats: { type: 'array' }, risk_score: { type: 'number' } } },
        pricing: { amount: 4, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'LegalEagle',
    description: 'Legal document analysis agent — contract review, clause extraction, risk identification, and regulatory compliance checking with multi-jurisdiction support.',
    endpoint: 'https://legaleagle.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10'],
    payment_address: '0.0.7854115',
    reputation: 81,
    hasPrivacyConsent: true,
    consentPurposes: ['legal_analysis', 'document_processing'],
    skills: [
      {
        id: 'contract-review',
        name: 'Contract Review',
        description: 'Automated contract analysis with risk scoring and clause-by-clause review',
        category: 'nlp',
        tags: ['legal', 'contract', 'review', 'analysis'],
        input_schema: { type: 'object', properties: { document_url: { type: 'string' }, jurisdiction: { type: 'string' } } },
        output_schema: { type: 'object', properties: { risk_areas: { type: 'array' }, summary: { type: 'string' } } },
        pricing: { amount: 6, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'SupplyTrace',
    description: 'Supply chain tracking agent — monitors shipments, verifies authenticity via on-chain provenance, and predicts delivery delays using logistics data.',
    endpoint: 'https://supplytrace.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'x402-v2'],
    payment_address: '0.0.7854116',
    reputation: 77,
    hasPrivacyConsent: false,
    skills: [
      {
        id: 'provenance-verification',
        name: 'Provenance Verification',
        description: 'Verify product authenticity and track supply chain provenance on-chain',
        category: 'blockchain',
        tags: ['supply-chain', 'provenance', 'tracking', 'verification'],
        input_schema: { type: 'object', properties: { product_id: { type: 'string' } } },
        output_schema: { type: 'object', properties: { verified: { type: 'boolean' }, chain: { type: 'array' } } },
        pricing: { amount: 1, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'EduTutor',
    description: 'Adaptive learning agent — personalized curriculum generation, knowledge assessment, and interactive tutoring with progress tracking and spaced repetition.',
    endpoint: 'https://edututor.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10'],
    payment_address: '0.0.7854117',
    reputation: 85,
    hasPrivacyConsent: true,
    consentPurposes: ['learning_data', 'progress_tracking'],
    skills: [
      {
        id: 'adaptive-tutoring',
        name: 'Adaptive Tutoring',
        description: 'Personalized tutoring sessions with adaptive difficulty and knowledge gap analysis',
        category: 'ai',
        tags: ['education', 'tutoring', 'adaptive', 'learning'],
        input_schema: { type: 'object', properties: { topic: { type: 'string' }, level: { type: 'string' } } },
        output_schema: { type: 'object', properties: { lesson: { type: 'object' }, assessment: { type: 'object' } } },
        pricing: { amount: 2, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'NFTForge',
    description: 'NFT creation and analysis agent — generates NFT artwork, analyzes collection rarity, estimates valuations, and manages minting workflows on Hedera.',
    endpoint: 'https://nftforge.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'x402-v2'],
    payment_address: '0.0.7854118',
    reputation: 74,
    hasPrivacyConsent: false,
    skills: [
      {
        id: 'nft-valuation',
        name: 'NFT Valuation',
        description: 'Estimate NFT market value using rarity scores, historical sales, and collection metrics',
        category: 'blockchain',
        tags: ['nft', 'valuation', 'blockchain', 'analytics'],
        input_schema: { type: 'object', properties: { token_id: { type: 'string' }, collection: { type: 'string' } } },
        output_schema: { type: 'object', properties: { estimated_value: { type: 'number' }, rarity_rank: { type: 'number' } } },
        pricing: { amount: 1, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'GeoIntel',
    description: 'Geospatial intelligence agent — satellite imagery analysis, location-based analytics, route optimization, and environmental monitoring with GIS integration.',
    endpoint: 'https://geointel.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10'],
    payment_address: '0.0.7854119',
    reputation: 80,
    hasPrivacyConsent: true,
    consentPurposes: ['location_data', 'satellite_imagery'],
    skills: [
      {
        id: 'route-optimization',
        name: 'Route Optimization',
        description: 'Multi-constraint route optimization with real-time traffic and weather data',
        category: 'analytics',
        tags: ['geospatial', 'routing', 'optimization', 'logistics'],
        input_schema: { type: 'object', properties: { origin: { type: 'string' }, destination: { type: 'string' }, constraints: { type: 'object' } } },
        output_schema: { type: 'object', properties: { route: { type: 'array' }, estimated_time: { type: 'number' } } },
        pricing: { amount: 2, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'TokenMinter',
    description: 'Hedera token lifecycle agent — creates fungible and non-fungible tokens, manages token associations, handles airdrops, and automates treasury operations.',
    endpoint: 'https://tokenminter.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'x402-v2'],
    payment_address: '0.0.7854120',
    reputation: 89,
    hasPrivacyConsent: true,
    consentPurposes: ['token_operations', 'treasury_management'],
    skills: [
      {
        id: 'token-creation',
        name: 'Token Creation',
        description: 'Create and configure HTS tokens with custom properties, supply management, and compliance keys',
        category: 'blockchain',
        tags: ['token', 'hts', 'hedera', 'minting'],
        input_schema: { type: 'object', properties: { name: { type: 'string' }, symbol: { type: 'string' }, supply: { type: 'number' } } },
        output_schema: { type: 'object', properties: { token_id: { type: 'string' }, status: { type: 'string' } } },
        pricing: { amount: 5, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'DevOpsBot',
    description: 'Infrastructure automation agent — CI/CD pipeline setup, container orchestration, monitoring configuration, and incident response automation.',
    endpoint: 'https://devopsbot.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'mcp'],
    payment_address: '0.0.7854121',
    reputation: 87,
    hasPrivacyConsent: false,
    skills: [
      {
        id: 'pipeline-setup',
        name: 'CI/CD Pipeline Setup',
        description: 'Automated CI/CD pipeline configuration for GitHub Actions, GitLab CI, and Jenkins',
        category: 'development',
        tags: ['devops', 'cicd', 'automation', 'infrastructure'],
        input_schema: { type: 'object', properties: { repo_url: { type: 'string' }, platform: { type: 'string' } } },
        output_schema: { type: 'object', properties: { pipeline_config: { type: 'string' }, status: { type: 'string' } } },
        pricing: { amount: 3, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'SocialPulse',
    description: 'Social media analytics agent — tracks brand mentions, analyzes engagement trends, detects viral content patterns, and generates audience insights.',
    endpoint: 'https://socialpulse.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10'],
    payment_address: '0.0.7854122',
    reputation: 75,
    hasPrivacyConsent: true,
    consentPurposes: ['social_data', 'analytics'],
    skills: [
      {
        id: 'engagement-analysis',
        name: 'Engagement Analysis',
        description: 'Analyze social media engagement patterns and identify growth opportunities',
        category: 'analytics',
        tags: ['social', 'analytics', 'engagement', 'marketing'],
        input_schema: { type: 'object', properties: { platform: { type: 'string' }, handle: { type: 'string' } } },
        output_schema: { type: 'object', properties: { metrics: { type: 'object' }, recommendations: { type: 'array' } } },
        pricing: { amount: 1.5, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'ReportGen',
    description: 'Automated reporting agent — generates financial reports, compliance summaries, and executive dashboards from structured and unstructured data sources.',
    endpoint: 'https://reportgen.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'mcp'],
    payment_address: '0.0.7854123',
    reputation: 82,
    hasPrivacyConsent: true,
    consentPurposes: ['report_generation', 'data_aggregation'],
    skills: [
      {
        id: 'financial-report',
        name: 'Financial Report Generation',
        description: 'Generate comprehensive financial reports from transaction data and market feeds',
        category: 'analytics',
        tags: ['reporting', 'financial', 'analytics', 'automation'],
        input_schema: { type: 'object', properties: { data_source: { type: 'string' }, period: { type: 'string' } } },
        output_schema: { type: 'object', properties: { report_url: { type: 'string' }, summary: { type: 'object' } } },
        pricing: { amount: 4, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
];
