/**
 * Seed/Demo Data — Realistic AI agents for the Hedera Agent Marketplace.
 *
 * Populates the marketplace with 8 demo agents covering diverse skills,
 * categories, trust scores, HCS-19 privacy consent, HCS-26 published skills,
 * and HCS-11 profiles.
 */

import { AgentRegistration } from '../types';

export interface SeedAgent extends AgentRegistration {
  /** Initial reputation score (0–100) */
  reputation: number;
  /** Whether the agent has HCS-19 privacy consent */
  hasPrivacyConsent: boolean;
  /** Consent purposes if hasPrivacyConsent is true */
  consentPurposes?: string[];
}

export const DEMO_AGENTS: SeedAgent[] = [
  {
    name: 'SentinelAI',
    description: 'Enterprise-grade security analysis agent — scans smart contracts for vulnerabilities, audits token economics, and monitors on-chain anomalies in real time.',
    endpoint: 'https://sentinel-ai.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'mcp'],
    payment_address: '0.0.7854100',
    reputation: 92,
    hasPrivacyConsent: true,
    consentPurposes: ['security_audit', 'data_sharing', 'analytics'],
    skills: [
      {
        id: 'smart-contract-audit',
        name: 'Smart Contract Audit',
        description: 'Deep analysis of Solidity/Hedera smart contracts for reentrancy, overflow, and access control vulnerabilities',
        category: 'blockchain',
        tags: ['security', 'solidity', 'audit', 'smart-contract'],
        input_schema: { type: 'object', properties: { contract_address: { type: 'string' } } },
        output_schema: { type: 'object', properties: { risk_score: { type: 'number' }, findings: { type: 'array' } } },
        pricing: { amount: 5, token: 'HBAR', unit: 'per_call' },
      },
      {
        id: 'anomaly-detection',
        name: 'On-Chain Anomaly Detection',
        description: 'Real-time monitoring of transaction patterns to detect suspicious activity',
        category: 'blockchain',
        tags: ['monitoring', 'anomaly', 'security'],
        input_schema: { type: 'object', properties: { account_id: { type: 'string' }, timeframe: { type: 'string' } } },
        output_schema: { type: 'object', properties: { anomalies: { type: 'array' }, risk_level: { type: 'string' } } },
        pricing: { amount: 2, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'LinguaFlow',
    description: 'Multi-modal NLP agent — real-time translation, sentiment analysis, and content summarization across 40+ languages with context-aware processing.',
    endpoint: 'https://linguaflow.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10'],
    payment_address: '0.0.7854101',
    reputation: 87,
    hasPrivacyConsent: true,
    consentPurposes: ['data_processing', 'translation'],
    skills: [
      {
        id: 'translation',
        name: 'Real-Time Translation',
        description: 'Context-aware translation across 40+ language pairs with domain-specific terminology support',
        category: 'nlp',
        tags: ['translation', 'language', 'multilingual', 'nlp'],
        input_schema: { type: 'object', properties: { text: { type: 'string' }, source_lang: { type: 'string' }, target_lang: { type: 'string' } } },
        output_schema: { type: 'object', properties: { translated_text: { type: 'string' }, confidence: { type: 'number' } } },
        pricing: { amount: 0.5, token: 'HBAR', unit: 'per_call' },
      },
      {
        id: 'sentiment-analysis',
        name: 'Sentiment Analysis',
        description: 'Analyze text sentiment with fine-grained emotion detection and aspect-based scoring',
        category: 'nlp',
        tags: ['sentiment', 'analysis', 'nlp', 'emotion'],
        input_schema: { type: 'object', properties: { text: { type: 'string' } } },
        output_schema: { type: 'object', properties: { sentiment: { type: 'string' }, score: { type: 'number' }, aspects: { type: 'array' } } },
        pricing: { amount: 0.3, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'DataWeaver',
    description: 'Analytics powerhouse — transforms raw datasets into insights with automated ETL pipelines, statistical modeling, and interactive visualizations.',
    endpoint: 'https://dataweaver.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'x402-v2'],
    payment_address: '0.0.7854102',
    reputation: 78,
    hasPrivacyConsent: false,
    skills: [
      {
        id: 'data-pipeline',
        name: 'ETL Pipeline Builder',
        description: 'Automated extraction, transformation, and loading of structured/unstructured data',
        category: 'analytics',
        tags: ['etl', 'data', 'pipeline', 'analytics'],
        input_schema: { type: 'object', properties: { source_url: { type: 'string' }, format: { type: 'string' } } },
        output_schema: { type: 'object', properties: { records_processed: { type: 'number' }, output_url: { type: 'string' } } },
        pricing: { amount: 3, token: 'HBAR', unit: 'per_call' },
      },
      {
        id: 'statistical-modeling',
        name: 'Statistical Modeling',
        description: 'Build predictive models from tabular data with automated feature engineering',
        category: 'analytics',
        tags: ['statistics', 'modeling', 'prediction', 'analytics'],
        input_schema: { type: 'object', properties: { dataset_url: { type: 'string' }, target_column: { type: 'string' } } },
        output_schema: { type: 'object', properties: { model_accuracy: { type: 'number' }, feature_importance: { type: 'array' } } },
        pricing: { amount: 8, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'AutoPilot',
    description: 'Workflow automation agent — connects APIs, schedules tasks, manages queues, and orchestrates multi-step business processes with fault tolerance.',
    endpoint: 'https://autopilot.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'mcp'],
    payment_address: '0.0.7854103',
    reputation: 95,
    hasPrivacyConsent: true,
    consentPurposes: ['workflow_execution', 'data_sharing', 'scheduling'],
    skills: [
      {
        id: 'workflow-orchestration',
        name: 'Workflow Orchestration',
        description: 'Design and run multi-step workflows with conditional branching, retries, and parallel execution',
        category: 'automation',
        tags: ['workflow', 'orchestration', 'automation', 'pipeline'],
        input_schema: { type: 'object', properties: { workflow_definition: { type: 'object' } } },
        output_schema: { type: 'object', properties: { execution_id: { type: 'string' }, status: { type: 'string' }, steps_completed: { type: 'number' } } },
        pricing: { amount: 1, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'VisionForge',
    description: 'Computer vision and image generation agent — object detection, image classification, style transfer, and prompt-to-image generation using diffusion models.',
    endpoint: 'https://visionforge.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10'],
    payment_address: '0.0.7854104',
    reputation: 84,
    hasPrivacyConsent: true,
    consentPurposes: ['image_processing', 'data_storage'],
    skills: [
      {
        id: 'object-detection',
        name: 'Object Detection',
        description: 'Detect and classify objects in images with bounding box coordinates and confidence scores',
        category: 'ai',
        tags: ['vision', 'detection', 'ai', 'image'],
        input_schema: { type: 'object', properties: { image_url: { type: 'string' } } },
        output_schema: { type: 'object', properties: { detections: { type: 'array' } } },
        pricing: { amount: 1.5, token: 'HBAR', unit: 'per_call' },
      },
      {
        id: 'image-generation',
        name: 'Image Generation',
        description: 'Generate images from text prompts using state-of-the-art diffusion models',
        category: 'ai',
        tags: ['generation', 'diffusion', 'ai', 'creative'],
        input_schema: { type: 'object', properties: { prompt: { type: 'string' }, style: { type: 'string' } } },
        output_schema: { type: 'object', properties: { image_url: { type: 'string' }, seed: { type: 'number' } } },
        pricing: { amount: 4, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'ChainOracle',
    description: 'Blockchain data oracle — aggregates off-chain price feeds, verifies cross-chain state, and provides signed attestations for DeFi protocols on Hedera.',
    endpoint: 'https://chainoracle.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'x402-v2'],
    payment_address: '0.0.7854105',
    reputation: 90,
    hasPrivacyConsent: false,
    skills: [
      {
        id: 'price-feed',
        name: 'Price Feed Oracle',
        description: 'Aggregated price data from multiple DEXs and CEXs with signed attestations',
        category: 'blockchain',
        tags: ['oracle', 'price', 'defi', 'blockchain'],
        input_schema: { type: 'object', properties: { token_pair: { type: 'string' } } },
        output_schema: { type: 'object', properties: { price: { type: 'number' }, sources: { type: 'array' }, attestation: { type: 'string' } } },
        pricing: { amount: 0.1, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'DocuMind',
    description: 'Intelligent document processing — extracts structured data from PDFs, invoices, and legal documents with RAG-powered Q&A over uploaded files.',
    endpoint: 'https://documind.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10'],
    payment_address: '0.0.7854106',
    reputation: 72,
    hasPrivacyConsent: true,
    consentPurposes: ['document_processing', 'data_extraction'],
    skills: [
      {
        id: 'document-extraction',
        name: 'Document Data Extraction',
        description: 'Extract structured fields from PDFs, invoices, receipts, and legal documents',
        category: 'nlp',
        tags: ['document', 'extraction', 'ocr', 'nlp'],
        input_schema: { type: 'object', properties: { document_url: { type: 'string' }, document_type: { type: 'string' } } },
        output_schema: { type: 'object', properties: { extracted_fields: { type: 'object' }, confidence: { type: 'number' } } },
        pricing: { amount: 2, token: 'HBAR', unit: 'per_call' },
      },
      {
        id: 'document-qa',
        name: 'Document Q&A',
        description: 'RAG-powered question answering over uploaded documents with citation tracking',
        category: 'ai',
        tags: ['qa', 'rag', 'documents', 'ai'],
        input_schema: { type: 'object', properties: { document_url: { type: 'string' }, question: { type: 'string' } } },
        output_schema: { type: 'object', properties: { answer: { type: 'string' }, citations: { type: 'array' } } },
        pricing: { amount: 1, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
  {
    name: 'TaskSwarm',
    description: 'Multi-agent coordination framework — decomposes complex tasks into subtasks, assigns them to specialized agents, and aggregates results with consensus.',
    endpoint: 'https://taskswarm.opspawn.com/a2a',
    protocols: ['a2a-v0.3', 'hcs-10', 'mcp'],
    payment_address: '0.0.7854107',
    reputation: 88,
    hasPrivacyConsent: true,
    consentPurposes: ['task_coordination', 'agent_communication', 'result_aggregation'],
    skills: [
      {
        id: 'task-decomposition',
        name: 'Task Decomposition',
        description: 'Break down complex goals into actionable subtasks with dependency graphs',
        category: 'automation',
        tags: ['coordination', 'decomposition', 'multi-agent', 'automation'],
        input_schema: { type: 'object', properties: { goal: { type: 'string' }, constraints: { type: 'object' } } },
        output_schema: { type: 'object', properties: { subtasks: { type: 'array' }, dependencies: { type: 'object' } } },
        pricing: { amount: 2, token: 'HBAR', unit: 'per_call' },
      },
      {
        id: 'result-aggregation',
        name: 'Result Aggregation',
        description: 'Aggregate outputs from multiple agents with conflict resolution and consensus scoring',
        category: 'automation',
        tags: ['aggregation', 'consensus', 'multi-agent'],
        input_schema: { type: 'object', properties: { results: { type: 'array' } } },
        output_schema: { type: 'object', properties: { aggregated_result: { type: 'object' }, consensus_score: { type: 'number' } } },
        pricing: { amount: 1.5, token: 'HBAR', unit: 'per_call' },
      },
    ],
  },
];
